version: '3.8'

services:
  whalepod:
    build:
      context: .
      dockerfile: Dockerfile
    image: growhaleystudio/whalepod:latest
    container_name: whalepod
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - ADMIN_USER=admin
      - ADMIN_PASS=admin
      - JWT_SECRET=whalepod-secure-random-jwt-key-2026
      - DATABASE_URL=file:/app/backend/prisma/dev.db
    volumes:
      - whalepod-data:/app/backend/prisma

volumes:
  whalepod-data:
