services:
  - type: web
    name: monitor-wp
    runtime: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 3000
      - key: JWT_SECRET
        generateValue: true
      - key: ADMIN_USER
        value: admin
      - key: ADMIN_PASS
        value: admin
